
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: helloworld
    name: helloworld
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: quay.io/eap-eks/helloworld:latest
                  imagePullPolicy: Always
                  name: helloworld
                  ports:
                    - containerPort: 8080
                  resources: {}
            imagePullSecrets:
                - name: quay-io-imagepullsecret
            restartPolicy: Always
            securityContext: {}
status: {}

...
